sudo: false
language: java
env:
  -   secure: "f78upMWhPViLh2W9jLjkjikZgSJCd9LuJVZF227JFSLGV8+DC0YbHQi6pYmpejhTT9H1OTqXyQ5c16QEQzutx6O63iyWdvWtIHtuct66jWPUp1NL3EAlK9F4NdG/9sbdEcElgrQxEArjYB5w+UZ+1uJucc1oMqIWbWQ089tvdx1VYZYRdP3pdLOoqgAqi4/GOxj8vRO9lIY7kc9IhEDDAfzNrGV8/LKao9f1pEOI+XcVDMOovRcstkMJZ5kqAep7xZTURGScKE6dMm58IEPDQAfbbGxAaJTO1HiNhFt6u2n+Z/oXZS8zlD/mcTA2acE6Ip7AMplSrac3bkzhwULwVu1PeDhteS9cwhpwJ/B3dR5sDAA+U/4WkfDV5VyyWVn8Z7Jy5nzDyUrtZBiPCzUyKDEaKc0mlLjWJjGiboq3ACnn62CE+VWQz9J0vnjxrwwqLcZbAtPzbFn3myYNbrf2qHt7n9eL3l9c9mkzYCfC6hz1oqsa35cimL6NXzjbRPu8ruyZdDcOdPBlVcdQ/g8ZhTslo5SCi4yukGQ0NbdPF0bJ4JXmBT49KUGbPOrCqdzoe+or04uJ6KkbLsO+bSGtVcidMuUeeylhfUBMtZs8XBKB2o3WWpZKjCUlKDl/vfDmlP7G+1Bd6lR11F1Z5jmtPLBzKlURrAMPVSk4EwFLNeQ="
jdk:
  - oraclejdk8
git:
  depth: 9999999
before_script:
  - git fetch origin master:master
  - git fetch origin test:test
  - git pull
  - git log --graph --full-history --all --color --date=short --pretty=format:"%Cred%x09%h %Creset%ad%Cgreen%d %Creset %s %C(bold)(%an)%Creset"
script:
  - ./gradlew build -DGITHUB_OAUTH2TOKEN=$GITHUB_OAUTH2TOKEN --stacktrace -i
after_script:
  - find -name TEST* -exec cat {} \;
notifications:
  email: false
