version: 2
shared: &shared
  steps:
    - run: java -version
    - checkout
    - run: ./gradlew build
jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    <<: *shared
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    <<: *shared
  jdk17:
    docker:
      - image: cimg/openjdk:17.0
    <<: *shared
workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
#      - jdk17
